### PR TITLE
Simplify pr variability driver

### PR DESCRIPTION
**Pull request by lee1043**
In this PR I've simplified the pr variability driver by modularizing metric calculation part.

### CODE REVIEW

**Comment by lee1043** [comment]
I have verified that the [demo 7](https://github.com/PCMDI/pcmdi_metrics/blob/main/doc/jupyter/Demo/Demo_7_precip_variability.ipynb) results (statistics numbers in output JSON) is not affected and remaining identical.

**Comment by msahn** [comment]
I tried to test this code on Gates by cloning this branch, and I found there is an issue to call 'pcmdi_metrics.precip_variability.lib' as below.
--------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ahn6/PCMDI/branch/lee1043_simplify_pr_variability_driver/pcmdi_metrics/pcmdi_metrics/precip_variability/scripts_pcmdi/../variability_across_timescales_PS_driver.py", line 10, in <module>
    from pcmdi_metrics.precip_variability.lib import (
ModuleNotFoundError: No module named 'pcmdi_metrics.precip_variability'
--------------------------------------------------------------------------------------------------------

I think this issue occurs after updating "pcmdi_metrics" to version 2.1.2. Could you check this issue?

**Comment by lee1043** [comment]
@msahn thanks for testing the revised scripts. Does that issue occurs with version 2.2.1 as well?

**Comment by lee1043** [comment]
@msahn could you try `import pcmdi_metrics` and share the result? Just curious if missing module is only precip_variability or others as well.

**Comment by msahn** [comment]
> @msahn thanks for testing the revised scripts. Does that issue occurs with version 2.2.1 as well?

I have tested it with pmp v2.2.1, and it is still not working, but the error message is changed. Below is the error message. It seems that "precip_variability_across_timescale" is not added in the file "/home/ahn6/anaconda3/envs/pmp_v20220110/lib/python3.9/site-packages/pcmdi_metrics/precip_variability/lib/__init__.py".

```
"log_PS_3hr_TRMM" 4L, 524C                                                                                                            4,1           All
Traceback (most recent call last):
  File "/home/ahn6/PCMDI/branch/lee1043_simplify_pr_variability_driver/pcmdi_metrics/pcmdi_metrics/precip_variability/scripts_pcmdi/../variability_across_timescales_PS_driver.py", line 10, in <module>
    from pcmdi_metrics.precip_variability.lib import (
ImportError: cannot import name 'precip_variability_across_timescale' from 'pcmdi_metrics.precip_variability.lib' (/home/ahn6/anaconda3/envs/pmp_v20220110/lib/python3.9/site-packages/pcmdi_metrics/precip_variability/lib/__init__.py)
```

**Comment by msahn** [comment]
> @msahn could you try `import pcmdi_metrics` and share the result? Just curious if missing module is only precip_variability or others as well.

`import pcmdi_metrics` is working well with pmp v2.2.1.

**Comment by lee1043** [comment]
@msahn helped identifying where the issue was coming from. It looks like once pmp installed through conda-forge, re-installing from cloned repo is not overwriting the pre-installed pmp. One work around is to generate development dedicated conda env (with all dependecies installed but pmp), following [here](https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers#test-development-branch-before-merging-its-pull-request-pr-to-main), then install pmp from the cloned repo, to test the branch in development. 

@msahn, once you confirm that driver is working correctly in your development env, could you please approve your review, so I can merge following the main branch protection protocol? (at least one review required for merging) Thanks!

**Comment by msahn** [comment]
> @msahn helped identifying where the issue was coming from. It looks like once pmp installed through conda-forge, re-installing from cloned repo is not overwriting the pre-installed pmp. One work around is to generate development dedicated conda env (with all dependecies installed but pmp), following [here](https://github.com/PCMDI/pcmdi_metrics/wiki/Tips-for-Developers#test-development-branch-before-merging-its-pull-request-pr-to-main), then install pmp from the cloned repo, to test the branch in development.
> 
> @msahn, once you confirm that driver is working correctly in your development env, could you please approve your review, so I can merge following the main branch protection protocol? (at least one review required for merging) Thanks!

I have tested this code in my pmp development env and confirmed that the results are identical to the previous version.

**Review by msahn — APPROVED** [review]
